### ISSUE TITLE
Can this project ESP8266 be used?

### ISSUE THREAD

**Issue by ZhiqiKou** [patrickcollins12/esphome-fan-controller#44]
If it cannot be used, where do I need to modify it? 
Thank you

**Comment by patrickcollins12** [comment]
yes it should work no problem. 
(esp32 is cheap though)

**Comment by patrickcollins12** [comment]
you need to update this to your device:

```
esp32:
  board: nodemcu-32s
  framework:
    type: arduino
```

**Comment by rommess** [comment]
changing framework make error.
changing output to "esp8266_pwm" compile the code.
```
output:
  # Wire this pin (13) into the PWM pin of your 12v fan
  # ledc is the name of the pwm output system on an esp32
  - platform: esp8266_pwm
     #ledc
    id: console_fan_speed
```
Did not test it yet fully wired.
